buildscript {
    ext.kotlin_version = '1.9.20'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // ✅ Android Gradle Plugin 버전 추가
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

ext.forcedKotlinStdlib = '1.9.20'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects { proj ->
    configurations.all { cfg ->
        // 옛 stdlib 모듈 싹 제외
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'

        // kotlin-stdlib 계열 버전 강제 통일
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                if (details.requested.name.startsWith('kotlin-stdlib')) {
                    details.useVersion forcedKotlinStdlib
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
